version: "3.6"
services:
  server:
    build:
      context: .
      target: development
    command: ["npm", "run", "dev"]
    container_name: server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      # essa porta é do serviço de debug do node (see package.json)
      - "${DEBUG_PORT}:${DEBUG_PORT}"
    volumes:
      - "./src:/usr/app/src"
